### ISSUE TITLE
[Todo] Drop method for classes

### ISSUE THREAD

**Issue by alshdavid** [alshdavid/BorrowScript#19]
What will this look like?

**Comment by alshdavid** [comment]
Maybe we could be cheeky and have a `destructor` on a class
```typescript
class Foo {
   constructor() {}
   destructor() {}
}
```

**Comment by SuperSonicHub1** [comment]
I like the `destructor` idea; much less boring than `drop`!

**Comment by mindplay-dk** [comment]
Since there's no garbage collector, destructors would act immediately when an object falls out of scope, right?

I've always felt like destructor were kind of "unfortunate side-effects", but in the context of a language with manual memory management, it might be a good feature for things like deallocating memory or closing file handles, etc.

**Comment by alshdavid** [comment]
>  it might be a good feature for things like deallocating memory or closing file handles, etc

This is exactly the use case. As an example, automatically unsubscribing from an observable when it falls out of scope.
```typescript
function foo(read source: Observable<string>) {
  const subscription = source.subscribe(console.log)
  //
  // ...code
  //
  // subscription.unsubscribe() is automatic
}
```
