### ISSUE TITLE
Why is `move` the default?

### ISSUE THREAD

**Issue by mindplay-dk** [alshdavid/BorrowScript#20]
The document says:

> `move` is the default if omitted

I am wondering why?

I would have assumed `read` would be the default, as this would encourage functional programming - if somebody wants to create code with mutations, they would use `copy`, `write` or `move` too specify "how".

That is, `read` appears to be the one that stands out from the other three, all of which are about how to deal with changing values - which, in my opinion, would seem to make it the logical candidate for a default.

I'm totally open to being wrong on this. 😄

I approach this from the perspective of a Typescript developer with no Rust experience.

Coming from Typescript, I don't normally have to think of memory management, and honestly never expected I would care or even like the Rust memory model, so let me explain:

I view these annotations as more than just memory management - in fact, it's nice that they work for compile-time memory management, but what really interests me is the idea of making it explicit what a function can be expected to do with your variable.

It surprises me how much I like this idea, and how easy it is to understand - it never exactly clicked for me in Rust, where for some reason this seemed burdensome to me. I'm not sure why. I might not have been receptive at the time and maybe I owe Rust a second look. But this looks great in the context of Typescript. 👍

I would probably even have found this meaningful in a language that only enforces these rules at compile-time and doesn't need them for memory management - such as Typescript.

Anyhow, if there's a good reason why `move` is the default, maybe this should be explained in that section of the spec?

**Comment by alshdavid** [comment]
Hey mindpay-dk, thanks for the issue/question/comment I enjoyed reading through it.  

> I would have assumed read would be the default, as this would encourage functional programming - if somebody wants to create code with mutations, they would use copy, write or move too specify "how".

I must admit initially I thought the same thing. In Rust, `move` is the default and the reason seems to be callbacks. If you imagine a callback that gives you a string:

```typescript
foo((aString: string) => {
   console.log(string)
})
``` 
Having the value as `read` only would probably be fine. If you wanted to modify it then just `copy` it and return a new value. This doesn't work when you have a callback that passes an object with methods on it. Take an express http server.
```typescript
app.get('', (req, res) => res.sendStatus(200))
```
We can assume that `res.sendStatus()` will behind the scenes modify some state before responding to the request. The same go for the `Promise` constructor:
```typescript
new Promise(res => res('Hello!'))
```
If `read` is the default then you would have to annotate these callbacks with `move`
```typescript
new Promise((move res) => res('Hello!'))
```

At this stage, I am not sure what is more burdensome. Writing `move` everywhere or writing `read` everywhere 😄 

> this would encourage functional programming

One of the many advantages of a functional programming approach is that immutability protects you from data races. Mutation is dangerous, particularly when parallel programming. 

Rust did something that no language before it has done. The concept of variable ownership tracked by the compiler that springs warnings you when you're making mutations from multiple places. The compiler forcing you to write safe code. 

This is annoying as heck and it's why Rust guarantees that "if your code compiles it works". In some ways ownership pushes people to write more functional style code because it's easier than dealing with mutation.

In a sense, Rust and it's ownership model is a new mixed paradigm language (functional and OO) that gives us the best of both worlds and uses the compiler to enforce integrity. Nothing like that has been done before which is why people have raved on about it but...

> it never exactly clicked for me in Rust, where for some reason this seemed burdensome to me. I'm not sure why.

This is how a lot of people feel about it. It's not because the borrow checker is complex, it's because they have `String` and `str`, which are two different string types. You have references, smart pointers and all this low level stuff that's great for writing an OS but really gets in the way when writing a web app.
 
> maybe I owe Rust a second look.

I would never discourage someone from learning more and if you do end up having a look at it, I hope that some of the ideas in this repo helped set the stage for you to pick Rust up quickly 🔢 

> I approach this from the perspective of a Typescript developer with no Rust experience.

A little background, I approached Rust after years of TypeScript because I wanted to use threads on the browser and not tear my (little remaining) hair out with Web Workers. I really appreciated the concepts of Rust and kept thinking "if only I could just write with TypeScript syntax".

**Comment by alshdavid** [comment]
Hey mindplay-dk, thanks for the issue/question/comment I enjoyed reading through it.  

> I would have assumed read would be the default, as this would encourage functional programming - if somebody wants to create code with mutations, they would use copy, write or move too specify "how".

I will be improving the documentation to clarify this but ownership permissions are specified by the implementations and not the caller. Meaning, if you write a function, your function specifies the permissions it requires.

Imagine you wrote an implementation of `map()` where you return a new instance of an array.
```typescript
// TypeScript
function map<T, U>(a: T[], cb: (value: T) => U): U[] { /* ... */ } 

// BorrowScript
function map<T, U>(read a: T[], move cb: (copy value: T) => U): U[] { /* ... */ } 
``` 
To break it down, our map function takes `read`  access to an array, give the caller a callback which is given a `copy` to the item in that array.

If I was to call this function from `main()`, even if I had `write` access to the array, I could only ever give this function `read` access because it cannot take anything other than that.

When we talk about `move` being the default, we mean the default for function parameter declarations. So in the above:
```typescript
function map<T, U>(read a: T[], move cb: (copy value: T) => U): U[] { /* ... */ } 

// you can remove "move" from "cb"
function map<T, U>(read a: T[], cb: (copy value: T) => U): U[] { /* ... */ } 
```

> it never exactly clicked for me in Rust, where for some reason this seemed burdensome to me. I'm not sure why.

This is how a lot of people feel about Rust. It's not because the borrow checker is complex, it's because they have `String` and `str`, which are two different string types. Read access is `&` and write is `&mut`. There are smart pointers and all this low level stuff that's great for writing an operating system but really gets in the way when writing a web app - particularly when you didn't have to deal with this stuff before.
 
> maybe I owe Rust a second look.

I would never discourage someone from learning more and if you do end up having a look at it, I hope that some of the ideas in this repo helped set the stage for you to pick Rust up quickly 🔢 

> I approach this from the perspective of a Typescript developer with no Rust experience.

A little background, I approached Rust after years of TypeScript because I wanted to use threads on the browser and not tear my (little remaining) hair out because of Web Workers. 

When we look at native apps and how smooth they are, a lot of that is because they are multi-threaded. I wanted to bring that smoothness to my projects. I wanted to have applications that weren't 800kb of minified JavaScript.

Learning Rust, I really appreciated the variable ownership concepts and kept thinking "if only I could just write with TypeScript syntax".

**Comment by mindplay-dk** [comment]
> When we talk about move being the default, we mean the default for function parameter declarations.

Yes, that's what I thought as well. 🙂

So in your example, someone who calls `map` will lose their own reference to `cb`, right?

And this is default for parameters?

The `move` effect is contagious, so I'm still not understanding why that would be the default - `read`, on the other hand, has no effects and makes things immutable by default, which seems like "a good thing".

> I wanted to have applications that weren't 800kb of minified JavaScript.

Amen to that. 🙏

> Learning Rust, I really appreciated the variable ownership concepts and kept thinking "if only I could just write with TypeScript syntax".

Deciding not to learn Rust, I kept thinking "if only it looked more like TypeScript" 😄

**Comment by zzzachzzz** [comment]
I was initially confused by `move` being the default. Then I remembered that it's the default in Rust, and in Rust we opt into `read` behavior with a non mutable reference `&param`. I think it could be helpful to include a section in the docs showing how BorrowScript's syntax maps over to Rust.

**Comment by alshdavid** [comment]
I have updated the main readme with details on how the `move` operator will function. 

As mentioned above, the default `move` action is an immutable (read only) move where you would need to specify a mutable move.

```
function foo(bar: string) {} // "bar" is immutable but moved into "foo"
function bar(move<let> foo: string) {} // "foo" is moved in as mutable
```

**Comment by shortercode** [comment]
The rust borrow checker has stronger restrictions on mutability as well as
deep mutability restrictions. I'm unsure if the reasoning for this is
related to concurrency or object lifecycles, but it's a good restriction to
have because let's be honest JS const is very weak.

**Comment by mindplay-dk** [comment]
> let's be honest JS const is very weak.

JS `const` works perfectly well for what I expect it to do - which is just to inform the reader whether they should expect a local symbol to get replaced or not. When I see `const`, I know I don't have to plow through the code to figure out what else ends up in that symbol.

*Should* a local declaration be able to enact restrictions on mutability on an object?

That seems like something the object should decide?

I don't even know how that would work? If an object has methods that mutate the object, and you make a local declaration saying this instance will be immutable - it still has that method, so now you get, what, compile-time or run-time errors for trying to do something the object said it would be able to do?

Would these constraints be able to taint as well? If so, it's beginning to sound a lot like [Pony](https://www.ponylang.io/) - a language with an extremely sharp learning curve, which kind of takes these ideas to the extreme. (I would hope that a language that borrows from TS would be more accessible to people without a computer science degree.)

**Comment by alshdavid** [comment]
> Or does `let` and `const` have somehow radically different semantics from JS/TS?

It works differently in BorrowScript. As you say `const` `let` in JS/TS refers to symbol assignment, but the value is mutable.
In BorrowScript they are aliases for `let` and `let mut` - so value mutability.

```typescript
const foo = 'Hi'
let bar = 'Hi'
```
is equivalent to 
```rust
let foo = String::from("hi")
let mut bar = String::from("hi")
```
